### ISSUE TITLE
Can't serve app built by angular-cli using command `ng serve --aot`

### ISSUE THREAD

**Issue by emolr** [apollostack/angular2-apollo#167]
Running `ng serve --aot` fails to run.

This is the console error:
```
* NG Live Development Server is running on http://localhost:4200. **
  0% compilingcan't resolve module apollo-client from /Users/Emil/Documents/Github/collab/collab/src/app/client.ts
can't find symbol undefined exported from module /Users/Emil/Documents/Github/collab/collab/node_modules/apollo-client/index.d.ts, resolving symbol AppModule in /Users/Emil/Documents/Github/collab/collab/src/app/app.module.ts, resolving symbol AppModule in /Users/Emil/Documents/Github/collab/collab/src/app/app.module.ts
Error: can't find symbol undefined exported from module /Users/Emil/Documents/Github/collab/collab/node_modules/apollo-client/index.d.ts, resolving symbol AppModule in /Users/Emil/Documents/Github/collab/collab/src/app/app.module.ts, resolving symbol AppModule in /Users/Emil/Documents/Github/collab/collab/src/app/app.module.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:532:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:536:20)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:93:28)
    at NgModuleResolver.resolve (/Users/Emil/Documents/Github/collab/collab/node_modules/@angular/compiler/bundles/compiler.umd.js:14050:46)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/Emil/Documents/Github/collab/collab/node_modules/@angular/compiler/bundles/compiler.umd.js:14296:49)
    at /Users/Emil/Documents/Github/collab/collab/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (/Users/Emil/Documents/Github/collab/collab/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
    at analyzeNgModules (/Users/Emil/Documents/Github/collab/collab/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
    at OfflineCompiler.compileModules (/Users/Emil/Documents/Github/collab/collab/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
    at AotPlugin._make (/Users/Emil/Documents/Github/collab/collab/node_modules/@ngtools/webpack/src/plugin.js:186:43)
    at Compiler.<anonymous> (/Users/Emil/Documents/Github/collab/collab/node_modules/@ngtools/webpack/src/plugin.js:151:75)
    at Compiler.applyPluginsParallel (/Users/Emil/Documents/Github/collab/collab/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/Users/Emil/Documents/Github/collab/collab/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:456:7)
    at Watching.<anonymous> (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:46:17)
    at next (/Users/Emil/Documents/Github/collab/collab/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.invalidAsyncPlugin (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack-dev-middleware/middleware.js:119:3)
    at next (/Users/Emil/Documents/Github/collab/collab/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/CachePlugin.js:31:4)
    at Compiler.applyPluginsAsync (/Users/Emil/Documents/Github/collab/collab/node_modules/tapable/lib/Tapable.js:85:13)
    at Watching._go (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.<anonymous> (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:36:8)
    at Compiler.readRecords (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:367:10)
    at new Watching (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:33:16)
    at Compiler.watch (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack/lib/Compiler.js:204:17)
    at module.exports (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack-dev-middleware/middleware.js:146:27)
    at new Server (/Users/Emil/Documents/Github/collab/collab/node_modules/webpack-dev-server/lib/Server.js:43:20)
    at Class.run (/Users/Emil/Documents/Github/collab/collab/node_modules/angular-cli/tasks/serve-webpack.js:72:22)
    at /Users/Emil/Documents/Github/collab/collab/node_modules/angular-cli/commands/serve.js:92:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I'm not sure, but it might be related to https://github.com/angular/angular/issues/11402

**Comment by kamilkisiela** [comment]
@emolr Try to load a client [like this](https://github.com/apollostack/angular2-apollo/blob/master/examples/hello-world/src/app/client.ts)

**Comment by kamilkisiela** [comment]
Basically, you can always take a look at the [HelloWorld example](https://github.com/apollostack/angular2-apollo/tree/master/examples/hello-world) and also on [GitHunt](github.com/apollostack/GitHunt-angular2)

**Comment by emolr** [comment]
Hey @kamilkisiela Thank you so much! 
It looked so similar to my client file that i didn't notice, but it did the trick! Thank you!
